version: '3.3'
services:
  drupal:
    image: drupal:latest 
    container_name: drupalWeb
    volumes:
     - drupal_modules:/var/www/html/modules
     - drupal_profiles:/var/www/html/profiles 
     - drupal_themes:/var/www/html/themes 
     - drupal_sites:/var/www/html/sites 
    restart: always
    depends_on:
      - db
    ports:
      - 8000:8000 
    networks:
      static-network:
        ipv4_address: 172.20.0.3
  db:
    image: postgres:latest
    container_name: postgresdb
    restart: always
    environment: 
      - POSTGRES_DB=shelter
      - POSTGRES_USER=futureproof
      - POSTGRES_PASSWORD=shelterpass
      
    ports:
    - 5432:5432
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    networks:
      static-network:
        ipv4_address: 172.20.0.2

    
volumes:
   drupal_modules:
   drupal_profiles:
   drupal_themes:
   drupal_sites:
   dbdata:
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          #docker-compose v3+ do not use ip_range
          ip_range: 172.28.5.0/24




