version: '3.3'
services:
  drupal:
    image: drupal:latest 
    container_name: drupalWeb
    volumes:
     - drupal_modules:/var/www/html/modules
     - drupal_profiles:/var/www/html/profiles 
     - drupal_themes:/var/www/html/themes 
     - drupal_sites:/var/www/html/sites 
    restart: always
    depends_on:
      - db
    ports:
      - 8000:8000 
    networks:
      static-network:
        ipv4_address: 172.20.0.3
  db:
    image: mysql:8.0
    container_name: mysqldb12345
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
    - 3306:3306
    volumes:
    - db_data:/var/lib/mysql
    networks:
      static-network:
        ipv4_address: 172.20.0.2
volumes:
   drupal_modules:
   drupal_profiles:
   drupal_themes:
   drupal_sites:
   db_data:
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          #docker-compose v3+ do not use ip_range
          ip_range: 172.28.5.0/24




